### ISSUE TITLE
Koodikatselmointi 2

### ISSUE THREAD

**Issue by Katri96** [MWargelin/Tsoha-Bootstrap#1]
07.10.2017 | 12:30

Luokat on nimetty asianmukaisesti ja metodeita on tarpeeksi ja ne ovat sopivan selkeitä ja lyhyitä. 
Luokat on jaoteltu hyvin kansioihin ja jokaisella luokalla on selkeä tarkoitus. Koodissa ei näy copy-pastea. Koodi noudattaa todella hyvin Clean code periaatetta. 
Kun muistilistaan lisää askareen ja antaa sille liian pitkän nimen, avautuu virheikkuna, sillä se yrittää lisätä otsikkoa askareen nimeksi, eikä vie virheilmoitukseen. Tämä kannattaa korjata.
Rekisteröityessä liian pitkän salasanan antaminen tuottaa myös virheilmoituksen, myös tähän kannattaa toteuttaa error ja ei hyväksyä rekisteröintiä.
Muuten ohjelma toimii hyvin ja sovellus vaikuttaa valmiilta.

**Comment by MWargelin** [comment]
Kiitos! Paneudun näihin ensi viikolla :)

**Comment by MWargelin** [comment]
Nämä bugit on nyt hoidettu. Kiitos vielä!
